name: Action di Casiroli
on: 
  push:
jobs:
  ciao:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "sudo shutdown"
      - run: echo "bub"
      - run: python --version
      - run: ifconfig
      - run: lsb_release -d
      - run: ls -la
      - run: pwd
      - run: env
      - uses: actions/checkout@v4
        with:
          sparse-checkout:
            casiroli
      - run: ls -la