name: Action di Casiroli
on: 
  push:

jobs:
  ciao:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "sudo shutdown"
      - run: echo "bub"
      - run: python --version
      - run: ifconfig  # sostituito ifconfig
      - run: lsb_rerelease -d # più affidabile di lsb_release
      - run: ls -la
      - run: pwd
      - run: env

      - uses: actions/checkout@v4
        with:
          sparse-checkout:
            - casiroli  # corretto formato

      - run: ls -la

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7' 

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: casiroli

      - run: python prediction_Forrest.py
        working-directory: casiroli

      - uses: actions/upload-artifact@v4
        with:
          name: artefatto
          path: casiroli/artefatto.joblib
